openapi: 3.0.3
info:
  version: 1.0.0
  title: What's for dinner?
  termsOfService: 'https://docs.whatsfordinner.dev/terms/'
  contact:
    email: contact@example.com
    url: 'https://docs.whatsfordinner.dev'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  x-logo:
    url: './wfd-logo.png'
  description:
    $ref: ./info-description.md
tags:
  - name: Listing ingredients
    description: |
      List ingredients on-hand, and an audit trail of ingredients.
  - name: Adding ingredients
    description: |
      Add ingredients one-by-one or by uploading photos of refrigerator, cabinet, pantry contents, or grocery receipts.

      What's for dinner parses uploaded photos and adds the ingredients to the kitchen.
  - name: Reducing ingredients
    description: |
      Cook, eat, donate, or discard ingredients.
  - name: Notifications
    description: |
      Get automated notifications when certain events occur.
      Respond with an HTTP status 2XX without any content to indicate receipt.

      WFD will retry webhook delivery with an exponential backoff for 24 hours.
servers:
  - url: 'https://api.whatsfordinner.dev'
paths:
  '/photos':
    $ref: 'paths/photos.yaml'
  '/ingredients':
    $ref: 'paths/ingredients.yaml'
  '/ingredients-reduction':
    $ref: 'paths/ingredients-reduction.yaml'
  '/available-ingredients/{kitchenId}':
    $ref: 'paths/available-ingredients@{kitchenId}.yaml'
  # '/ingredients-audit':
  #   $ref: 'paths/ingredients-audit.yaml'
x-webhooks:
  three-day-expiration-warning:
    post:
      $ref: ./components/webhooks/three-day-expiration-warning.yaml

components:
  securitySchemes:
    auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'http://example.com/api/oauth/dialog'
          scopes:
            'read:kitchen': read kitchen ingredients
            'write:kitchen': modify kitchen ingredients
